global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # ModelVS3 API 服务
  - job_name: 'modelvs3-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Prometheus 自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:8090']

  # 如果有其他服务，可以在这里添加
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379'] 