"""add tool calls to chat messages

Revision ID: 006_add_tool_calls_to_chat_messages
Revises: 005_add_chat_history_tables
Create Date: 2025-07-25 15:42:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006_add_tool_calls_to_chat_messages'
down_revision = '005_add_chat_history_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tool_calls', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_messages', sa.Column('tool_call_id', sa.String(), nullable=True))
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('chat_messages', 'tool_call_id')
    op.drop_column('chat_messages', 'tool_calls')
    # ### end Alembic commands ###