"""Add api_key and custom_headers to models table

Revision ID: 3c63e77f6c23
Revises: 003
Create Date: 2025-07-21 10:40:08.532979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c63e77f6c23'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('models', sa.Column('custom_headers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'custom_headers')
    op.drop_column('models', 'api_key')
    # ### end Alembic commands ### 